version: "3.6"
services:
  php72_cli:
    build:
      context: "./7.2-cli"
  php72_fpm:
    build:
      context: "./7.2-fpm"
    environment:
      - PHP_UPLOAD_MAX_FILEZISE=128M
      - PHP_POST_MAX_SIZE=128M
      - PHP_MEMORY_LIMIT=128M
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MAX_INPUT_TIME=30
  php_latest_cli:
    build:
      context: "./latest-cli"
  php_latest_fpm:
    build:
      context: "./latest-fpm"
    environment:
      - PHP_UPLOAD_MAX_FILEZISE=128M
      - PHP_POST_MAX_SIZE=128M
      - PHP_MEMORY_LIMIT=128M
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MAX_INPUT_TIME=30